# Generated by Django 3.2.15 on 2023-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_mesage_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
