# Generated by Django 3.2.15 on 2023-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
